baseURL: "https://xenodochial-swirles-49b2f2.netlify.app"
#baseURL: "https://example.com"
languageCode: "en-us"
title: Slotman game
pygmentsstyle: monokai
tags: ["new", "popular", "table", "live", "other", "slot", "jackpot"]

# Theme settings

params:
  logo: /images/logo.png
  favicon: /images/favicon.ico
  email: support@slotman.com
  site: https://www.slotman.com/
  ga: UA-163602877-1
  gtm: GTM-WM3JSMN

paginate: 6
social:
  facebook: "https://www.facebook.com/slotman.casino"
  instagram: "#"
  youtube: "#"
  
taxonomies:
  author: authors
  tag: tags
  category: categories
